table orders
	lineageTag: 87438ded-2e23-4b86-8fd0-5f30a5ca3563

	measure 'Total Orders' = DISTINCTCOUNT('orders'[order_id])
		formatString: 0
		lineageTag: 8d140a10-f63d-46c8-bc7a-167e2cf4688c

	measure 'Conversion Rate' = DIVIDE([Total Orders], [Total_Sessions], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e1abfb56-4367-4784-a7a8-07ecadd69e5d

	measure 'Total Customers' = DISTINCTCOUNT('orders'[user_id])
		formatString: 0
		lineageTag: f737aad2-289b-4c57-9c72-11a70efa651e

	measure 'Repeat Customers' =
			
			COUNTROWS(
			    FILTER(
			        VALUES('orders'[user_id]),
			        CALCULATE(COUNT('orders'[order_id])) > 1
			    )
			)
		formatString: 0
		lineageTag: abb8d6f3-1525-4539-84f5-c7a91e979c5f

	measure 'New Customers' = [Total Customers] - [Repeat Customers]
		formatString: 0
		lineageTag: c7d31d19-01d6-47e2-a148-6a6fd4e92b1a

	measure 'Net Profit' =
			
			VAR GrossRevenue = SUM('orders'[price_usd])
			VAR TotalCOGS = SUM('orders'[cogs_usd])
			VAR TotalRefunds = SUM('order_item_refunds'[refund_amount_usd])
			RETURN
			    (GrossRevenue - TotalCOGS) - TotalRefunds
		lineageTag: 713ea055-592d-4566-9d67-261850893ede

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order_id
		dataType: int64
		formatString: 0
		lineageTag: f0933066-f969-4846-9741-4fd01731b51d
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 38dc0b5d-fdbd-4852-847d-8afd199f9e15
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: 66ca2c0b-49a6-4169-99a4-0fc9af03ded4
			defaultHierarchy: LocalDateTable_a3469d56-7241-43a9-a569-afe018696b11.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column website_session_id
		dataType: int64
		formatString: 0
		lineageTag: 813257c8-cc05-42a9-afc7-4a619fba511d
		summarizeBy: none
		sourceColumn: website_session_id

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: int64
		formatString: 0
		lineageTag: 144ce593-d49c-454a-9774-b104317e3254
		summarizeBy: sum
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column primary_product_id
		dataType: int64
		formatString: 0
		lineageTag: 5f235b61-f870-4443-b23e-b46832e7a4a0
		summarizeBy: sum
		sourceColumn: primary_product_id

		annotation SummarizationSetBy = Automatic

	column items_purchased
		dataType: int64
		formatString: 0
		lineageTag: 6ab9cf54-af80-4f41-9ac2-e0908546eb38
		summarizeBy: sum
		sourceColumn: items_purchased

		annotation SummarizationSetBy = Automatic

	column price_usd
		dataType: double
		lineageTag: 02a4b76f-6b7e-4fdb-8520-d04dbbd6c308
		summarizeBy: sum
		sourceColumn: price_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cogs_usd
		dataType: double
		lineageTag: eb899e0c-1992-4fe5-909c-ee4cc1415677
		summarizeBy: sum
		sourceColumn: cogs_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day of Week' = FORMAT('orders'[created_at], "dddd")
		lineageTag: d65b0cb4-c317-4063-9895-2758659eccb6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\datasets\Maven+Fuzzy+Factory maven\website_pageviews full.xlsx"), null, true),
				    orders_Sheet = Source{[Item="orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", Int64.Type}, {"created_at", type datetime}, {"website_session_id", Int64.Type}, {"user_id", Int64.Type}, {"primary_product_id", Int64.Type}, {"items_purchased", Int64.Type}, {"price_usd", type number}, {"cogs_usd", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

