table website_pageviews
	lineageTag: 8fd1885d-0c4b-4bbf-83ea-3f75e4f05f2d

	measure 'Cart Abandonment Rate' = ```
			
			VAR CartSessions = 
			    CALCULATE(
			        DISTINCTCOUNT('website_pageviews'[website_session_id]),
			        'website_pageviews'[pageview_url] = "/cart"
			    )
			VAR CompletedOrders = [Total Orders]
			
			RETURN
			    DIVIDE(CartSessions - CompletedOrders, CartSessions, 0)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a98e1912-7f19-482b-909a-505c48bd0b53

	column website_pageview_id
		dataType: int64
		formatString: 0
		lineageTag: 8d496baf-38cf-4f8d-8f4d-4d1124143b8b
		summarizeBy: sum
		sourceColumn: website_pageview_id

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 20089ab6-7c04-4724-9f16-9a9c6266e774
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: 4ad8e74c-7f25-40d2-bbe3-bb63d161f6ae
			defaultHierarchy: LocalDateTable_0a378d34-0c64-4219-a75e-da1c38bdea18.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column website_session_id
		dataType: int64
		formatString: 0
		lineageTag: e4f50cbf-ef6a-4a84-9cad-357c36fb27bb
		summarizeBy: none
		sourceColumn: website_session_id

		annotation SummarizationSetBy = Automatic

	column pageview_url
		dataType: string
		lineageTag: a5c2bfad-b639-423e-822a-c1ca358c1d56
		summarizeBy: none
		sourceColumn: pageview_url

		annotation SummarizationSetBy = Automatic

	column 'Funnel Stage' =
			
			SWITCH(
			    TRUE(),
			    CONTAINSSTRING('website_pageviews'[pageview_url], "home") || CONTAINSSTRING('website_pageviews'[pageview_url], "lander"), "Landing",
			    CONTAINSSTRING('website_pageviews'[pageview_url], "products"), "Product_List",
			    CONTAINSSTRING('website_pageviews'[pageview_url], "fuzzy") || CONTAINSSTRING('website_pageviews'[pageview_url], "forever") || CONTAINSSTRING('website_pageviews'[pageview_url], "sugar") || CONTAINSSTRING('website_pageviews'[pageview_url], "hudson"), "Product_Detail",
			    CONTAINSSTRING('website_pageviews'[pageview_url], "cart"), "Cart",
			    CONTAINSSTRING('website_pageviews'[pageview_url], "shipping"), "Shipping",
			    CONTAINSSTRING('website_pageviews'[pageview_url], "billing"), "Billing",
			    CONTAINSSTRING('website_pageviews'[pageview_url], "thank-you-for-your-order"), "Purchase",
			    "Other"
			)
		lineageTag: d8778e34-119b-4a0e-8ca6-4a6f880982d5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition website_pageviews = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\datasets\Maven+Fuzzy+Factory maven\website_pageviews full.xlsx"), null, true),
				    website_pageviews_Sheet = Source{[Item="website_pageviews",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(website_pageviews_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"website_pageview_id", Int64.Type}, {"created_at", type datetime}, {"website_session_id", Int64.Type}, {"pageview_url", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

